import { Tool } from '../constants';
import type { AbilityKey } from './skillAbility';

export const TOOL_ABILITY: Record<Tool, AbilityKey> = {
  [Tool.alchemistsSupplies]: 'int',
  [Tool.brewersSupplies]: 'int',
  [Tool.calligraphersSupplies]: 'dex',
  [Tool.carpentersTools]: 'str',
  [Tool.cartographersTools]: 'int',
  [Tool.cobblersTools]: 'dex',
  [Tool.cooksUtensils]: 'wis',
  [Tool.glassblowersTools]: 'int',
  [Tool.jewelersTools]: 'int',
  [Tool.leatherworkersTools]: 'dex',
  [Tool.masonsTools]: 'str',
  [Tool.paintersSupplies]: 'wis',
  [Tool.pottersTools]: 'int',
  [Tool.smithsTools]: 'str',
  [Tool.tinkersTools]: 'dex',
  [Tool.weaversTools]: 'dex',
  [Tool.woodcarversTools]: 'dex',
  [Tool.disguiseKit]: 'cha',
  [Tool.forgeryKit]: 'dex',
  [Tool.herbalismKit]: 'int',
  [Tool.navigatorsTools]: 'wis',
  [Tool.poisonersKit]: 'int',
  [Tool.thievesTools]: 'dex',
  [Tool.bagpipes]: 'cha',
  [Tool.drum]: 'cha',
  [Tool.dulcimer]: 'cha',
  [Tool.flute]: 'cha',
  [Tool.horn]: 'cha',
  [Tool.lute]: 'cha',
  [Tool.lyre]: 'cha',
  [Tool.panFlute]: 'cha',
  [Tool.shawm]: 'cha',
  [Tool.viol]: 'cha',
};
