const stringArray = { type: 'array', items: { type: 'string' } } as const;

const abilities = {
  str: { type: 'integer' },
  dex: { type: 'integer' },
  con: { type: 'integer' },
  int: { type: 'integer' },
  wis: { type: 'integer' },
  cha: { type: 'integer' },
} as const;

export const schemas = {
  Error: {
    type: 'object',
    required: ['error'],
    properties: {
      error: { type: 'string' },
    },
  },

  LocationKind: {
    type: 'string',
    enum: ['region', 'settlement', 'district', 'building', 'room', 'dungeon', 'wilderness', 'other'],
  },
  KnowledgeReveal: {
    type: 'string',
    enum: ['open', 'check', 'hidden'],
  },
  MemoryKind: {
    type: 'string',
    enum: ['episode', 'fact', 'favor', 'grievance', 'promise'],
  },
  ItemKind: {
    type: 'string',
    enum: ['weapon', 'armor', 'shield', 'tool', 'gear', 'consumable', 'treasure', 'key', 'junk', 'other'],
  },
  EquipSlot: {
    type: 'string',
    enum: ['armor', 'mainHand', 'offHand', 'ranged'],
  },
  WeaponMastery: {
    type: 'string',
    enum: ['cleave', 'graze', 'nick', 'push', 'sap', 'slow', 'topple', 'vex'],
  },
  ItemProp: {
    oneOf: [
      {
        type: 'object',
        required: ['type', 'text', 'dice'],
        properties: {
          type: { type: 'string', enum: ['damage'] },
          text: { type: 'string' },
          dice: { type: 'string' },
          damageType: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text', 'normal'],
        properties: {
          type: { type: 'string', enum: ['range'] },
          text: { type: 'string' },
          normal: { type: 'number' },
          long: { type: 'number' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text', 'base', 'addDex'],
        properties: {
          type: { type: 'string', enum: ['ac'] },
          text: { type: 'string' },
          base: { type: 'number' },
          addDex: { type: 'boolean' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text', 'dice'],
        properties: {
          type: { type: 'string', enum: ['heal'] },
          text: { type: 'string' },
          dice: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text'],
        properties: {
          type: { type: 'string', enum: ['twoHanded'] },
          text: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text'],
        properties: {
          type: { type: 'string', enum: ['stealthDisadvantage'] },
          text: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text', 'mastery'],
        properties: {
          type: { type: 'string', enum: ['mastery'] },
          text: { type: 'string' },
          mastery: { $ref: '#/components/schemas/WeaponMastery' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text'],
        properties: {
          type: { type: 'string', enum: ['ranged'] },
          text: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text'],
        properties: {
          type: { type: 'string', enum: ['finesse'] },
          text: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['type', 'text'],
        properties: {
          type: { type: 'string', enum: ['note'] },
          text: { type: 'string' },
        },
      },
    ],
  },
  ItemRarity: {
    type: 'string',
    enum: ['common', 'uncommon', 'rare', 'veryRare', 'legendary', 'artifact'],
  },
  QuestStatus: {
    type: 'string',
    enum: ['available', 'active', 'done', 'failed'],
  },
  QuestNpcRole: {
    type: 'string',
    enum: ['giver', 'participant', 'target', 'witness'],
  },
  DiceKind: {
    type: 'string',
    enum: ['d4', 'd6', 'd8', 'd10', 'd12', 'd20', 'd100'],
  },

  Campaign: {
    type: 'object',
    required: ['id', 'name', 'description', 'dayIndex', 'timeOfDay'],
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      description: { type: 'string', nullable: true },
      dayIndex: { type: 'integer' },
      timeOfDay: {
        type: 'string',
        enum: ['morning', 'noon', 'afternoon', 'evening', 'lateEvening', 'midnight', 'night'],
      },
    },
  },
  CreateCampaign: {
    type: 'object',
    required: ['name'],
    properties: {
      name: { type: 'string' },
      description: { type: 'string', nullable: true },
    },
  },
  UpdateCampaign: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      description: { type: 'string', nullable: true },
    },
  },

  Location: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'parentId',
      'kind',
      'name',
      'summary',
      'description',
      'features',
      'isSecret',
      'tags',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      parentId: { type: 'string', nullable: true },
      kind: { $ref: '#/components/schemas/LocationKind' },
      name: { type: 'string' },
      summary: { type: 'string' },
      description: { type: 'string' },
      features: { type: 'string' },
      isSecret: { type: 'boolean' },
      tags: stringArray,
    },
  },
  CreateLocation: {
    type: 'object',
    required: ['campaignId', 'parentId', 'kind', 'name', 'summary', 'description', 'features', 'tags'],
    properties: {
      campaignId: { type: 'string' },
      parentId: { type: 'string', nullable: true },
      kind: { $ref: '#/components/schemas/LocationKind' },
      name: { type: 'string' },
      summary: { type: 'string' },
      description: { type: 'string' },
      features: { type: 'string' },
      isSecret: { type: 'boolean' },
      tags: stringArray,
    },
  },
  UpdateLocation: {
    type: 'object',
    properties: {
      parentId: { type: 'string', nullable: true },
      kind: { $ref: '#/components/schemas/LocationKind' },
      name: { type: 'string' },
      summary: { type: 'string' },
      description: { type: 'string' },
      features: { type: 'string' },
      isSecret: { type: 'boolean' },
      tags: stringArray,
    },
  },

  Item: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'name',
      'kind',
      'rarity',
      'description',
      'weight',
      'valueCp',
      'coinsCp',
      'quantity',
      'catalogKey',
      'isMagical',
      'properties',
      'equipSlot',
      'playerId',
      'npcId',
      'locationId',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      name: { type: 'string' },
      kind: { $ref: '#/components/schemas/ItemKind' },
      rarity: { allOf: [{ $ref: '#/components/schemas/ItemRarity' }], nullable: true },
      description: { type: 'string' },
      weight: { type: 'number', nullable: true },
      valueCp: { type: 'integer', nullable: true },
      coinsCp: { type: 'integer' },
      quantity: { type: 'integer' },
      catalogKey: { type: 'string', nullable: true },
      isMagical: { type: 'boolean' },
      properties: { type: 'array', items: { $ref: '#/components/schemas/ItemProp' }, nullable: true },
      equipSlot: { allOf: [{ $ref: '#/components/schemas/EquipSlot' }], nullable: true },
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
      locationId: { type: 'string', nullable: true },
    },
  },
  CreateItem: {
    type: 'object',
    required: [
      'campaignId',
      'name',
      'kind',
      'description',
      'rarity',
      'weight',
      'valueCp',
      'properties',
      'playerId',
      'npcId',
      'locationId',
    ],
    properties: {
      campaignId: { type: 'string' },
      name: { type: 'string' },
      kind: { $ref: '#/components/schemas/ItemKind' },
      rarity: { allOf: [{ $ref: '#/components/schemas/ItemRarity' }], nullable: true },
      description: { type: 'string' },
      weight: { type: 'number', nullable: true },
      valueCp: { type: 'integer', nullable: true },
      coinsCp: { type: 'integer' },
      quantity: { type: 'integer' },
      catalogKey: { type: 'string', nullable: true },
      isMagical: { type: 'boolean' },
      properties: { type: 'array', items: { $ref: '#/components/schemas/ItemProp' }, nullable: true },
      equipSlot: { allOf: [{ $ref: '#/components/schemas/EquipSlot' }], nullable: true },
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
      locationId: { type: 'string', nullable: true },
    },
  },
  UpdateItem: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      kind: { $ref: '#/components/schemas/ItemKind' },
      rarity: { allOf: [{ $ref: '#/components/schemas/ItemRarity' }], nullable: true },
      description: { type: 'string' },
      weight: { type: 'number', nullable: true },
      valueCp: { type: 'integer', nullable: true },
      coinsCp: { type: 'integer' },
      quantity: { type: 'integer' },
      catalogKey: { type: 'string', nullable: true },
      isMagical: { type: 'boolean' },
      properties: { type: 'array', items: { $ref: '#/components/schemas/ItemProp' }, nullable: true },
      equipSlot: { allOf: [{ $ref: '#/components/schemas/EquipSlot' }], nullable: true },
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
      locationId: { type: 'string', nullable: true },
    },
  },
  EquipItem: {
    type: 'object',
    required: ['itemId', 'slot'],
    properties: {
      itemId: { type: 'string' },
      slot: { $ref: '#/components/schemas/EquipSlot' },
    },
  },
  UnequipItem: {
    type: 'object',
    required: ['itemId'],
    properties: {
      itemId: { type: 'string' },
    },
  },
  GrantCatalogItem: {
    type: 'object',
    required: ['playerId', 'key'],
    properties: {
      playerId: { type: 'string' },
      key: { type: 'string' },
      quantity: { type: 'integer', minimum: 1 },
    },
  },
  EquipItemResult: {
    type: 'object',
    required: ['item', 'unequipped'],
    properties: {
      item: { $ref: '#/components/schemas/Item' },
      unequipped: { type: 'array', items: { $ref: '#/components/schemas/Item' } },
    },
  },
  TakeItem: {
    type: 'object',
    required: ['playerId', 'itemId'],
    properties: {
      playerId: { type: 'string' },
      itemId: { type: 'string' },
    },
  },
  DropItem: {
    type: 'object',
    required: ['playerId', 'itemId'],
    properties: {
      playerId: { type: 'string' },
      itemId: { type: 'string' },
    },
  },
  ApplyPlayerHp: {
    type: 'object',
    required: ['delta'],
    properties: {
      delta: { type: 'integer' },
    },
  },
  ApplyPlayerHpResult: {
    type: 'object',
    required: ['playerId', 'hpMax', 'hpCurrent', 'hpTemp', 'conditions', 'exhaustionLevel'],
    properties: {
      playerId: { type: 'string' },
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      hpTemp: { type: 'integer' },
      conditions: { type: 'array', items: { type: 'string' } },
      exhaustionLevel: { type: 'integer' },
      dead: { type: 'boolean' },
    },
  },
  PlayerRest: {
    type: 'object',
    required: ['kind'],
    properties: {
      kind: { type: 'string', enum: ['short', 'long'] },
      hitDice: { type: 'integer' },
    },
  },
  PlayerRestResult: {
    type: 'object',
    required: ['playerId', 'hpMax', 'hpCurrent', 'hpTemp', 'hitDiceLeft', 'conditions', 'exhaustionLevel'],
    properties: {
      playerId: { type: 'string' },
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      hpTemp: { type: 'integer' },
      hitDiceLeft: { type: 'integer' },
      conditions: { type: 'array', items: { type: 'string' } },
      exhaustionLevel: { type: 'integer' },
      dead: { type: 'boolean' },
      healed: { type: 'integer' },
      dice: {
        type: 'array',
        items: {
          type: 'object',
          required: ['die', 'value', 'conMod'],
          properties: {
            die: { type: 'string' },
            value: { type: 'integer' },
            conMod: { type: 'integer' },
          },
        },
      },
    },
  },

  Player: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'name',
      'species',
      'className',
      'subclass',
      'background',
      'level',
      'xp',
      'alignment',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'hpTemp',
      'hitDie',
      'hitDiceLeft',
      'ac',
      'speed',
      'initiativeBonus',
      'proficiencyBonus',
      'inspiration',
      'deathSaveSuccess',
      'deathSaveFail',
      'armorProf',
      'weaponProf',
      'toolProf',
      'languages',
      'skillProf',
      'skillExpertise',
      'saveProf',
      'features',
      'spells',
      'notes',
      'portraitUrl',
      'coinsCp',
      'conditions',
      'exhaustionLevel',
      'dead',
      'locationId',
      'travelDestinationId',
      'travelRoute',
      'travelLegIndex',
      'travelDaysLeft',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      name: { type: 'string' },
      species: { type: 'string' },
      className: { type: 'string' },
      subclass: { type: 'string', nullable: true },
      background: { type: 'string' },
      level: { type: 'integer' },
      xp: { type: 'integer', nullable: true },
      alignment: { type: 'string', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      hpTemp: { type: 'integer' },
      hitDie: { type: 'string' },
      hitDiceLeft: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      proficiencyBonus: { type: 'integer' },
      inspiration: { type: 'boolean' },
      deathSaveSuccess: { type: 'integer' },
      deathSaveFail: { type: 'integer' },
      armorProf: stringArray,
      weaponProf: stringArray,
      toolProf: stringArray,
      languages: stringArray,
      skillProf: stringArray,
      skillExpertise: stringArray,
      saveProf: stringArray,
      features: {},
      spells: {},
      notes: { type: 'string', nullable: true },
      portraitUrl: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
      conditions: stringArray,
      exhaustionLevel: { type: 'integer' },
      dead: { type: 'boolean' },
      locationId: { type: 'string', nullable: true },
      travelDestinationId: { type: 'string', nullable: true },
      travelRoute: { type: 'array', items: { type: 'string' }, nullable: true },
      travelLegIndex: { type: 'integer', nullable: true },
      travelDaysLeft: { type: 'integer', nullable: true },
    },
  },
  CreatePlayer: {
    type: 'object',
    required: [
      'campaignId',
      'name',
      'species',
      'className',
      'subclass',
      'background',
      'level',
      'xp',
      'alignment',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'hitDie',
      'hitDiceLeft',
      'ac',
      'speed',
      'initiativeBonus',
      'proficiencyBonus',
      'armorProf',
      'weaponProf',
      'toolProf',
      'languages',
      'skillProf',
      'skillExpertise',
      'saveProf',
      'features',
      'spells',
      'notes',
      'portraitUrl',
    ],
    properties: {
      campaignId: { type: 'string' },
      name: { type: 'string' },
      species: { type: 'string' },
      className: { type: 'string' },
      subclass: { type: 'string', nullable: true },
      background: { type: 'string' },
      level: { type: 'integer' },
      xp: { type: 'integer', nullable: true },
      alignment: { type: 'string', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      hpTemp: { type: 'integer' },
      hitDie: { type: 'string' },
      hitDiceLeft: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      proficiencyBonus: { type: 'integer' },
      inspiration: { type: 'boolean' },
      deathSaveSuccess: { type: 'integer' },
      deathSaveFail: { type: 'integer' },
      armorProf: stringArray,
      weaponProf: stringArray,
      toolProf: stringArray,
      languages: stringArray,
      skillProf: stringArray,
      skillExpertise: stringArray,
      saveProf: stringArray,
      features: {},
      spells: {},
      notes: { type: 'string', nullable: true },
      portraitUrl: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
      conditions: stringArray,
      exhaustionLevel: { type: 'integer' },
      dead: { type: 'boolean' },
      locationId: { type: 'string', nullable: true },
    },
  },
  UpdatePlayer: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      species: { type: 'string' },
      className: { type: 'string' },
      subclass: { type: 'string', nullable: true },
      background: { type: 'string' },
      level: { type: 'integer' },
      xp: { type: 'integer', nullable: true },
      alignment: { type: 'string', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      hpTemp: { type: 'integer' },
      hitDie: { type: 'string' },
      hitDiceLeft: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      proficiencyBonus: { type: 'integer' },
      inspiration: { type: 'boolean' },
      deathSaveSuccess: { type: 'integer' },
      deathSaveFail: { type: 'integer' },
      armorProf: stringArray,
      weaponProf: stringArray,
      toolProf: stringArray,
      languages: stringArray,
      skillProf: stringArray,
      skillExpertise: stringArray,
      saveProf: stringArray,
      features: {},
      spells: {},
      notes: { type: 'string', nullable: true },
      portraitUrl: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
      conditions: stringArray,
      exhaustionLevel: { type: 'integer' },
      dead: { type: 'boolean' },
      locationId: { type: 'string', nullable: true },
    },
  },

  PlayerTravel: {
    type: 'object',
    required: ['destinationId', 'destination', 'route', 'legIndex', 'daysLeft'],
    properties: {
      destinationId: { type: 'string' },
      destination: { $ref: '#/components/schemas/Location' },
      route: { type: 'array', items: { type: 'string' } },
      legIndex: { type: 'integer' },
      daysLeft: { type: 'integer' },
    },
  },
  PlayerLocation: {
    type: 'object',
    required: ['playerId', 'location', 'travel'],
    properties: {
      playerId: { type: 'string' },
      location: { allOf: [{ $ref: '#/components/schemas/Location' }], nullable: true },
      travel: { allOf: [{ $ref: '#/components/schemas/PlayerTravel' }], nullable: true },
    },
  },
  SetPlayerLocation: {
    type: 'object',
    required: ['playerId', 'locationId'],
    properties: {
      playerId: { type: 'string' },
      locationId: { type: 'string' },
    },
  },
  AdvanceTravel: {
    type: 'object',
    required: ['playerId'],
    properties: {
      playerId: { type: 'string' },
      days: { type: 'integer', minimum: 1 },
    },
  },

  LocationLink: {
    type: 'object',
    required: ['id', 'campaignId', 'fromId', 'toId', 'days', 'label'],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      fromId: { type: 'string' },
      toId: { type: 'string' },
      days: { type: 'integer' },
      label: { type: 'string', nullable: true },
    },
  },
  CreateLocationLink: {
    type: 'object',
    required: ['campaignId', 'fromId', 'toId', 'days'],
    properties: {
      campaignId: { type: 'string' },
      fromId: { type: 'string' },
      toId: { type: 'string' },
      days: { type: 'integer' },
      label: { type: 'string', nullable: true },
    },
  },
  UpdateLocationLink: {
    type: 'object',
    properties: {
      fromId: { type: 'string' },
      toId: { type: 'string' },
      days: { type: 'integer' },
      label: { type: 'string', nullable: true },
    },
  },

  Npc: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'name',
      'title',
      'appearance',
      'personality',
      'speech',
      'habits',
      'attitude',
      'dmNotes',
      'coinsCp',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      name: { type: 'string' },
      title: { type: 'string', nullable: true },
      appearance: { type: 'string' },
      personality: { type: 'string' },
      speech: { type: 'string' },
      habits: { type: 'string' },
      attitude: { type: 'string', nullable: true },
      dmNotes: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
    },
  },
  CreateNpc: {
    type: 'object',
    required: ['campaignId', 'name', 'title', 'appearance', 'personality', 'speech', 'habits', 'attitude', 'dmNotes'],
    properties: {
      campaignId: { type: 'string' },
      name: { type: 'string' },
      title: { type: 'string', nullable: true },
      appearance: { type: 'string' },
      personality: { type: 'string' },
      speech: { type: 'string' },
      habits: { type: 'string' },
      attitude: { type: 'string', nullable: true },
      dmNotes: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
    },
  },
  UpdateNpc: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      title: { type: 'string', nullable: true },
      appearance: { type: 'string' },
      personality: { type: 'string' },
      speech: { type: 'string' },
      habits: { type: 'string' },
      attitude: { type: 'string', nullable: true },
      dmNotes: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
    },
  },

  NpcKnowledge: {
    type: 'object',
    required: ['id', 'npcId', 'title', 'content', 'reveal', 'skillHint', 'dc', 'questId'],
    properties: {
      id: { type: 'string' },
      npcId: { type: 'string' },
      title: { type: 'string' },
      content: { type: 'string' },
      reveal: { $ref: '#/components/schemas/KnowledgeReveal' },
      skillHint: { type: 'string', nullable: true },
      dc: { type: 'integer', nullable: true },
      questId: { type: 'string', nullable: true },
    },
  },
  CreateNpcKnowledgeBody: {
    type: 'object',
    required: ['title', 'content', 'reveal', 'skillHint', 'dc', 'questId'],
    properties: {
      title: { type: 'string' },
      content: { type: 'string' },
      reveal: { $ref: '#/components/schemas/KnowledgeReveal' },
      skillHint: { type: 'string', nullable: true },
      dc: { type: 'integer', nullable: true },
      questId: { type: 'string', nullable: true },
    },
  },
  UpdateNpcKnowledge: {
    type: 'object',
    properties: {
      title: { type: 'string' },
      content: { type: 'string' },
      reveal: { $ref: '#/components/schemas/KnowledgeReveal' },
      skillHint: { type: 'string', nullable: true },
      dc: { type: 'integer', nullable: true },
      questId: { type: 'string', nullable: true },
    },
  },

  NpcRelation: {
    type: 'object',
    required: ['npcId', 'playerId', 'score', 'note'],
    properties: {
      npcId: { type: 'string' },
      playerId: { type: 'string' },
      score: { type: 'integer', minimum: -100, maximum: 100 },
      note: { type: 'string', nullable: true },
    },
  },
  SetNpcRelationBody: {
    type: 'object',
    required: ['score'],
    properties: {
      score: { type: 'integer', minimum: -100, maximum: 100 },
      note: { type: 'string', nullable: true },
    },
  },

  NpcMemory: {
    type: 'object',
    required: ['id', 'npcId', 'playerId', 'aboutNpcId', 'summary', 'kind', 'importance'],
    properties: {
      id: { type: 'string' },
      npcId: { type: 'string' },
      playerId: { type: 'string', nullable: true },
      aboutNpcId: { type: 'string', nullable: true },
      summary: { type: 'string' },
      kind: { $ref: '#/components/schemas/MemoryKind' },
      importance: { type: 'integer', minimum: 1, maximum: 5 },
    },
  },
  CreateNpcMemoryBody: {
    type: 'object',
    required: ['summary', 'kind'],
    properties: {
      playerId: { type: 'string', nullable: true },
      aboutNpcId: { type: 'string', nullable: true },
      summary: { type: 'string' },
      kind: { $ref: '#/components/schemas/MemoryKind' },
      importance: { type: 'integer', minimum: 1, maximum: 5 },
    },
  },
  UpdateNpcMemory: {
    type: 'object',
    properties: {
      playerId: { type: 'string', nullable: true },
      aboutNpcId: { type: 'string', nullable: true },
      summary: { type: 'string' },
      kind: { $ref: '#/components/schemas/MemoryKind' },
      importance: { type: 'integer', minimum: 1, maximum: 5 },
    },
  },

  NpcAtLocation: {
    type: 'object',
    required: ['npc', 'role', 'isPrimary'],
    properties: {
      npc: { $ref: '#/components/schemas/Npc' },
      role: { type: 'string', nullable: true },
      isPrimary: { type: 'boolean' },
    },
  },
  NpcLocation: {
    type: 'object',
    required: ['npcId', 'locationId', 'role', 'isPrimary'],
    properties: {
      npcId: { type: 'string' },
      locationId: { type: 'string' },
      role: { type: 'string', nullable: true },
      isPrimary: { type: 'boolean' },
    },
  },
  SetNpcLocationBody: {
    type: 'object',
    required: ['locationId'],
    properties: {
      locationId: { type: 'string' },
      role: { type: 'string', nullable: true },
      isPrimary: { type: 'boolean' },
    },
  },

  NpcStatBlock: {
    type: 'object',
    required: [
      'id',
      'npcId',
      'size',
      'creatureType',
      'challengeRating',
      'proficiencyBonus',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'ac',
      'speed',
      'initiativeBonus',
      'saveProf',
      'resistances',
      'immunities',
      'vulnerabilities',
      'conditionImmunities',
      'senses',
      'languages',
      'traits',
      'actions',
      'reactions',
      'legendaryActions',
    ],
    properties: {
      id: { type: 'string' },
      npcId: { type: 'string' },
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
    },
  },
  UpsertNpcStatBlockBody: {
    type: 'object',
    required: [
      'size',
      'creatureType',
      'challengeRating',
      'proficiencyBonus',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'ac',
      'speed',
      'initiativeBonus',
      'saveProf',
      'resistances',
      'immunities',
      'vulnerabilities',
      'conditionImmunities',
      'senses',
      'languages',
      'traits',
      'actions',
      'reactions',
      'legendaryActions',
    ],
    properties: {
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
    },
  },

  CombatStats: {
    type: 'object',
    required: [
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'ac',
      'speed',
      'saveProf',
      'resistances',
      'immunities',
      'vulnerabilities',
      'conditionImmunities',
      'senses',
      'languages',
    ],
    properties: {
      name: { type: 'string' },
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
    },
  },

  Quest: {
    type: 'object',
    required: ['id', 'campaignId', 'title', 'description', 'status', 'locationId'],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      title: { type: 'string' },
      description: { type: 'string' },
      status: { $ref: '#/components/schemas/QuestStatus' },
      locationId: { type: 'string', nullable: true },
    },
  },
  CreateQuest: {
    type: 'object',
    required: ['campaignId', 'title', 'description', 'locationId'],
    properties: {
      campaignId: { type: 'string' },
      title: { type: 'string' },
      description: { type: 'string' },
      status: { $ref: '#/components/schemas/QuestStatus' },
      locationId: { type: 'string', nullable: true },
    },
  },
  UpdateQuest: {
    type: 'object',
    properties: {
      title: { type: 'string' },
      description: { type: 'string' },
      status: { $ref: '#/components/schemas/QuestStatus' },
      locationId: { type: 'string', nullable: true },
    },
  },

  QuestNpc: {
    type: 'object',
    required: ['questId', 'npcId', 'role'],
    properties: {
      questId: { type: 'string' },
      npcId: { type: 'string' },
      role: { $ref: '#/components/schemas/QuestNpcRole' },
    },
  },
  AddQuestNpcBody: {
    type: 'object',
    required: ['npcId', 'role'],
    properties: {
      npcId: { type: 'string' },
      role: { $ref: '#/components/schemas/QuestNpcRole' },
    },
  },

  DiceRoll: {
    type: 'object',
    required: ['id', 'campaignId', 'die', 'value', 'note', 'playerId', 'npcId', 'rolledAt'],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      die: { $ref: '#/components/schemas/DiceKind' },
      value: { type: 'integer' },
      note: { type: 'string', nullable: true },
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
      rolledAt: { type: 'string', format: 'date-time' },
    },
  },
  RollDice: {
    type: 'object',
    required: ['campaignId', 'die'],
    properties: {
      campaignId: { type: 'string' },
      die: { $ref: '#/components/schemas/DiceKind' },
      note: { type: 'string', nullable: true },
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
    },
  },

  CoinOwnerKind: {
    type: 'string',
    enum: ['player', 'npc', 'item'],
  },
  CoinOwner: {
    type: 'object',
    required: ['kind', 'id'],
    properties: {
      kind: { $ref: '#/components/schemas/CoinOwnerKind' },
      id: { type: 'string' },
    },
  },
  Coins: {
    type: 'object',
    required: ['pp', 'gp', 'ep', 'sp', 'cp'],
    properties: {
      pp: { type: 'integer' },
      gp: { type: 'integer' },
      ep: { type: 'integer' },
      sp: { type: 'integer' },
      cp: { type: 'integer' },
    },
  },
  CoinBalance: {
    type: 'object',
    required: ['owner', 'coinsCp', 'coins'],
    properties: {
      owner: { $ref: '#/components/schemas/CoinOwner' },
      coinsCp: { type: 'integer' },
      coins: { $ref: '#/components/schemas/Coins' },
    },
  },
  TransferCoins: {
    type: 'object',
    required: ['campaignId', 'from', 'to', 'amountCp'],
    properties: {
      campaignId: { type: 'string' },
      from: { $ref: '#/components/schemas/CoinOwner' },
      to: { $ref: '#/components/schemas/CoinOwner' },
      amountCp: { type: 'integer' },
    },
  },
  TransferCoinsResult: {
    type: 'object',
    required: ['from', 'to', 'amountCp'],
    properties: {
      from: { $ref: '#/components/schemas/CoinBalance' },
      to: { $ref: '#/components/schemas/CoinBalance' },
      amountCp: { type: 'integer' },
    },
  },

  NpcChatMessage: {
    type: 'object',
    required: ['role', 'content'],
    properties: {
      role: { type: 'string', enum: ['user', 'assistant'] },
      content: { type: 'string' },
    },
  },
  NpcChatRequest: {
    type: 'object',
    required: ['campaignId', 'npcId', 'playerId', 'messages'],
    properties: {
      campaignId: { type: 'string' },
      npcId: { type: 'string' },
      playerId: { type: 'string' },
      messages: { type: 'array', items: { $ref: '#/components/schemas/NpcChatMessage' } },
    },
  },
  NpcChatReply: {
    type: 'object',
    required: ['say', 'do', 'toolCalls', 'turnId'],
    properties: {
      say: { type: 'string' },
      do: { type: 'string', nullable: true },
      check: { $ref: '#/components/schemas/RequestedCheck' },
      toolCalls: {
        type: 'array',
        items: { $ref: '#/components/schemas/NpcChatToolCall' },
      },
      turnId: { type: 'string' },
    },
  },
  NpcChatToolCall: {
    type: 'object',
    required: ['name', 'args', 'ok'],
    properties: {
      name: { type: 'string' },
      args: {},
      ok: { type: 'boolean' },
      result: {},
      error: { type: 'string' },
    },
  },
  MasterRequest: {
    type: 'object',
    required: ['campaignId', 'playerId', 'messages'],
    properties: {
      campaignId: { type: 'string' },
      playerId: { type: 'string' },
      messages: { type: 'array', items: { $ref: '#/components/schemas/NpcChatMessage' } },
    },
  },
  MasterReply: {
    type: 'object',
    required: ['verdict', 'say', 'toolCalls'],
    properties: {
      verdict: { type: 'string', enum: ['allowed', 'denied', 'partial', 'check', 'defer_combat'] },
      say: { type: 'string' },
      check: { $ref: '#/components/schemas/RequestedCheck' },
      toolCalls: {
        type: 'array',
        items: { $ref: '#/components/schemas/NpcChatToolCall' },
      },
    },
  },
  NpcChatHookRun: {
    type: 'object',
    required: ['turnId', 'name', 'status', 'toolCalls'],
    properties: {
      turnId: { type: 'string' },
      name: { type: 'string' },
      status: { type: 'string', enum: ['running', 'done', 'failed'] },
      toolCalls: {
        type: 'array',
        items: { $ref: '#/components/schemas/NpcChatToolCall' },
      },
      error: { type: 'string' },
    },
  },
  NpcChatHooksReply: {
    type: 'object',
    required: ['hooks'],
    properties: {
      hooks: {
        type: 'array',
        items: { $ref: '#/components/schemas/NpcChatHookRun' },
      },
    },
  },

  PlanStep: {
    oneOf: [
      {
        type: 'object',
        required: ['agent', 'npcId', 'npcName'],
        properties: {
          agent: { type: 'string', enum: ['npc'] },
          npcId: { type: 'string' },
          npcName: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['agent'],
        properties: {
          agent: { type: 'string', enum: ['master'] },
        },
      },
    ],
  },
  PlanRequest: {
    type: 'object',
    required: ['campaignId', 'playerId', 'messages'],
    properties: {
      campaignId: { type: 'string' },
      playerId: { type: 'string' },
      messages: { type: 'array', items: { $ref: '#/components/schemas/NpcChatMessage' } },
    },
  },
  PlanReply: {
    type: 'object',
    required: ['steps', 'toolCalls'],
    properties: {
      steps: {
        type: 'array',
        items: { $ref: '#/components/schemas/PlanStep' },
      },
      toolCalls: {
        type: 'array',
        items: { $ref: '#/components/schemas/NpcChatToolCall' },
      },
    },
  },

  LocationLookRequest: {
    type: 'object',
    required: ['campaignId', 'playerId'],
    properties: {
      campaignId: { type: 'string' },
      playerId: { type: 'string' },
      locationId: { type: 'string' },
      message: { type: 'string' },
    },
  },
  LocationLookReply: {
    type: 'object',
    required: ['look', 'locationId', 'turnId'],
    properties: {
      look: { type: 'string' },
      locationId: { type: 'string' },
      turnId: { type: 'string' },
    },
  },

  TurnRequest: {
    type: 'object',
    required: ['campaignId', 'playerId', 'messages'],
    properties: {
      campaignId: { type: 'string' },
      playerId: { type: 'string' },
      messages: { type: 'array', items: { $ref: '#/components/schemas/NpcChatMessage' } },
      resume: { $ref: '#/components/schemas/TurnResume' },
      check: { $ref: '#/components/schemas/TurnCheckInput' },
      rollId: { type: 'string' },
    },
  },
  RequestedCheck: {
    type: 'object',
    required: ['skill', 'dc'],
    properties: {
      skill: { type: 'string' },
      dc: { type: 'number' },
      knowledgeId: { type: 'string', nullable: true },
    },
  },
  TurnCheck: {
    type: 'object',
    required: ['skill', 'skillLabel', 'dc', 'bonus', 'die'],
    properties: {
      skill: { type: 'string' },
      skillLabel: { type: 'string' },
      dc: { type: 'number' },
      bonus: { type: 'number' },
      die: { type: 'string', enum: ['d20'] },
      knowledgeId: { type: 'string', nullable: true },
    },
  },
  TurnCheckInput: {
    type: 'object',
    required: ['skill', 'dc'],
    properties: {
      skill: { type: 'string' },
      dc: { type: 'number' },
      knowledgeId: { type: 'string', nullable: true },
    },
  },
  TurnResume: {
    oneOf: [
      {
        type: 'object',
        required: ['agent', 'npcId', 'remainingSteps'],
        properties: {
          agent: { type: 'string', enum: ['npc'] },
          npcId: { type: 'string' },
          remainingSteps: {
            type: 'array',
            items: { $ref: '#/components/schemas/PlanStep' },
          },
        },
      },
      {
        type: 'object',
        required: ['agent', 'remainingSteps'],
        properties: {
          agent: { type: 'string', enum: ['master'] },
          remainingSteps: {
            type: 'array',
            items: { $ref: '#/components/schemas/PlanStep' },
          },
        },
      },
    ],
  },
  TurnAgentReply: {
    oneOf: [
      {
        type: 'object',
        required: ['agent', 'locationId', 'name', 'isSecret', 'description', 'summary', 'features'],
        properties: {
          agent: { type: 'string', enum: ['location'] },
          locationId: { type: 'string' },
          name: { type: 'string' },
          isSecret: { type: 'boolean' },
          description: { type: 'string' },
          summary: { type: 'string' },
          features: { type: 'string' },
        },
      },
      {
        type: 'object',
        required: ['agent', 'npcId', 'npcName', 'say', 'do'],
        properties: {
          agent: { type: 'string', enum: ['npc'] },
          npcId: { type: 'string' },
          npcName: { type: 'string' },
          say: { type: 'string' },
          do: { type: 'string', nullable: true },
        },
      },
      {
        type: 'object',
        required: ['agent', 'verdict', 'say', 'toolCalls'],
        properties: {
          agent: { type: 'string', enum: ['master'] },
          verdict: { type: 'string', enum: ['allowed', 'denied', 'partial', 'check', 'defer_combat'] },
          say: { type: 'string' },
          toolCalls: {
            type: 'array',
            items: { $ref: '#/components/schemas/NpcChatToolCall' },
          },
        },
      },
    ],
  },
  TurnReply: {
    type: 'object',
    required: ['status', 'replies'],
    properties: {
      status: { type: 'string', enum: ['done', 'need_check'] },
      replies: {
        type: 'array',
        items: { $ref: '#/components/schemas/TurnAgentReply' },
      },
      check: { $ref: '#/components/schemas/TurnCheck' },
      resume: { $ref: '#/components/schemas/TurnResume' },
    },
  },
} as const;
