const stringArray = { type: 'array', items: { type: 'string' } } as const;

const abilities = {
  str: { type: 'integer' },
  dex: { type: 'integer' },
  con: { type: 'integer' },
  int: { type: 'integer' },
  wis: { type: 'integer' },
  cha: { type: 'integer' },
} as const;

export const schemas = {
  Error: {
    type: 'object',
    required: ['error'],
    properties: {
      error: { type: 'string' },
    },
  },

  LocationKind: {
    type: 'string',
    enum: ['region', 'settlement', 'district', 'building', 'room', 'dungeon', 'wilderness', 'other'],
  },
  KnowledgeReveal: {
    type: 'string',
    enum: ['open', 'check', 'hidden'],
  },
  MemoryKind: {
    type: 'string',
    enum: ['episode', 'fact', 'favor', 'grievance', 'promise'],
  },
  ItemKind: {
    type: 'string',
    enum: ['weapon', 'armor', 'shield', 'tool', 'gear', 'consumable', 'treasure', 'key', 'junk', 'other'],
  },
  ItemRarity: {
    type: 'string',
    enum: ['common', 'uncommon', 'rare', 'veryRare', 'legendary', 'artifact'],
  },
  QuestStatus: {
    type: 'string',
    enum: ['available', 'active', 'done', 'failed'],
  },
  QuestNpcRole: {
    type: 'string',
    enum: ['giver', 'participant', 'target', 'witness'],
  },
  DiceKind: {
    type: 'string',
    enum: ['d4', 'd6', 'd8', 'd10', 'd12', 'd20', 'd100'],
  },

  Campaign: {
    type: 'object',
    required: ['id', 'name', 'description'],
    properties: {
      id: { type: 'string' },
      name: { type: 'string' },
      description: { type: 'string', nullable: true },
    },
  },
  CreateCampaign: {
    type: 'object',
    required: ['name'],
    properties: {
      name: { type: 'string' },
      description: { type: 'string', nullable: true },
    },
  },
  UpdateCampaign: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      description: { type: 'string', nullable: true },
    },
  },

  Location: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'parentId',
      'kind',
      'name',
      'summary',
      'description',
      'features',
      'isSecret',
      'tags',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      parentId: { type: 'string', nullable: true },
      kind: { $ref: '#/components/schemas/LocationKind' },
      name: { type: 'string' },
      summary: { type: 'string' },
      description: { type: 'string' },
      features: { type: 'string' },
      isSecret: { type: 'boolean' },
      tags: stringArray,
    },
  },
  CreateLocation: {
    type: 'object',
    required: ['campaignId', 'parentId', 'kind', 'name', 'summary', 'description', 'features', 'tags'],
    properties: {
      campaignId: { type: 'string' },
      parentId: { type: 'string', nullable: true },
      kind: { $ref: '#/components/schemas/LocationKind' },
      name: { type: 'string' },
      summary: { type: 'string' },
      description: { type: 'string' },
      features: { type: 'string' },
      isSecret: { type: 'boolean' },
      tags: stringArray,
    },
  },
  UpdateLocation: {
    type: 'object',
    properties: {
      parentId: { type: 'string', nullable: true },
      kind: { $ref: '#/components/schemas/LocationKind' },
      name: { type: 'string' },
      summary: { type: 'string' },
      description: { type: 'string' },
      features: { type: 'string' },
      isSecret: { type: 'boolean' },
      tags: stringArray,
    },
  },

  Item: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'name',
      'kind',
      'rarity',
      'description',
      'weight',
      'valueCp',
      'coinsCp',
      'quantity',
      'isMagical',
      'properties',
      'playerId',
      'npcId',
      'locationId',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      name: { type: 'string' },
      kind: { $ref: '#/components/schemas/ItemKind' },
      rarity: { allOf: [{ $ref: '#/components/schemas/ItemRarity' }], nullable: true },
      description: { type: 'string' },
      weight: { type: 'number', nullable: true },
      valueCp: { type: 'integer', nullable: true },
      coinsCp: { type: 'integer' },
      quantity: { type: 'integer' },
      isMagical: { type: 'boolean' },
      properties: {},
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
      locationId: { type: 'string', nullable: true },
    },
  },
  CreateItem: {
    type: 'object',
    required: [
      'campaignId',
      'name',
      'kind',
      'description',
      'rarity',
      'weight',
      'valueCp',
      'properties',
      'playerId',
      'npcId',
      'locationId',
    ],
    properties: {
      campaignId: { type: 'string' },
      name: { type: 'string' },
      kind: { $ref: '#/components/schemas/ItemKind' },
      rarity: { allOf: [{ $ref: '#/components/schemas/ItemRarity' }], nullable: true },
      description: { type: 'string' },
      weight: { type: 'number', nullable: true },
      valueCp: { type: 'integer', nullable: true },
      coinsCp: { type: 'integer' },
      quantity: { type: 'integer' },
      isMagical: { type: 'boolean' },
      properties: {},
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
      locationId: { type: 'string', nullable: true },
    },
  },
  UpdateItem: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      kind: { $ref: '#/components/schemas/ItemKind' },
      rarity: { allOf: [{ $ref: '#/components/schemas/ItemRarity' }], nullable: true },
      description: { type: 'string' },
      weight: { type: 'number', nullable: true },
      valueCp: { type: 'integer', nullable: true },
      coinsCp: { type: 'integer' },
      quantity: { type: 'integer' },
      isMagical: { type: 'boolean' },
      properties: {},
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
      locationId: { type: 'string', nullable: true },
    },
  },

  Player: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'name',
      'species',
      'className',
      'subclass',
      'background',
      'level',
      'xp',
      'alignment',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'hpTemp',
      'hitDie',
      'hitDiceLeft',
      'ac',
      'speed',
      'initiativeBonus',
      'proficiencyBonus',
      'inspiration',
      'deathSaveSuccess',
      'deathSaveFail',
      'armorProf',
      'weaponProf',
      'toolProf',
      'languages',
      'skillProf',
      'skillExpertise',
      'saveProf',
      'features',
      'spells',
      'notes',
      'portraitUrl',
      'coinsCp',
      'conditions',
      'exhaustionLevel',
      'locationId',
      'travelDestinationId',
      'travelRoute',
      'travelLegIndex',
      'travelDaysLeft',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      name: { type: 'string' },
      species: { type: 'string' },
      className: { type: 'string' },
      subclass: { type: 'string', nullable: true },
      background: { type: 'string' },
      level: { type: 'integer' },
      xp: { type: 'integer', nullable: true },
      alignment: { type: 'string', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      hpTemp: { type: 'integer' },
      hitDie: { type: 'string' },
      hitDiceLeft: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      proficiencyBonus: { type: 'integer' },
      inspiration: { type: 'boolean' },
      deathSaveSuccess: { type: 'integer' },
      deathSaveFail: { type: 'integer' },
      armorProf: stringArray,
      weaponProf: stringArray,
      toolProf: stringArray,
      languages: stringArray,
      skillProf: stringArray,
      skillExpertise: stringArray,
      saveProf: stringArray,
      features: {},
      spells: {},
      notes: { type: 'string', nullable: true },
      portraitUrl: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
      conditions: stringArray,
      exhaustionLevel: { type: 'integer' },
      locationId: { type: 'string', nullable: true },
      travelDestinationId: { type: 'string', nullable: true },
      travelRoute: { type: 'array', items: { type: 'string' }, nullable: true },
      travelLegIndex: { type: 'integer', nullable: true },
      travelDaysLeft: { type: 'integer', nullable: true },
    },
  },
  CreatePlayer: {
    type: 'object',
    required: [
      'campaignId',
      'name',
      'species',
      'className',
      'subclass',
      'background',
      'level',
      'xp',
      'alignment',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'hitDie',
      'hitDiceLeft',
      'ac',
      'speed',
      'initiativeBonus',
      'proficiencyBonus',
      'armorProf',
      'weaponProf',
      'toolProf',
      'languages',
      'skillProf',
      'skillExpertise',
      'saveProf',
      'features',
      'spells',
      'notes',
      'portraitUrl',
    ],
    properties: {
      campaignId: { type: 'string' },
      name: { type: 'string' },
      species: { type: 'string' },
      className: { type: 'string' },
      subclass: { type: 'string', nullable: true },
      background: { type: 'string' },
      level: { type: 'integer' },
      xp: { type: 'integer', nullable: true },
      alignment: { type: 'string', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      hpTemp: { type: 'integer' },
      hitDie: { type: 'string' },
      hitDiceLeft: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      proficiencyBonus: { type: 'integer' },
      inspiration: { type: 'boolean' },
      deathSaveSuccess: { type: 'integer' },
      deathSaveFail: { type: 'integer' },
      armorProf: stringArray,
      weaponProf: stringArray,
      toolProf: stringArray,
      languages: stringArray,
      skillProf: stringArray,
      skillExpertise: stringArray,
      saveProf: stringArray,
      features: {},
      spells: {},
      notes: { type: 'string', nullable: true },
      portraitUrl: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
      conditions: stringArray,
      exhaustionLevel: { type: 'integer' },
      locationId: { type: 'string', nullable: true },
    },
  },
  UpdatePlayer: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      species: { type: 'string' },
      className: { type: 'string' },
      subclass: { type: 'string', nullable: true },
      background: { type: 'string' },
      level: { type: 'integer' },
      xp: { type: 'integer', nullable: true },
      alignment: { type: 'string', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      hpTemp: { type: 'integer' },
      hitDie: { type: 'string' },
      hitDiceLeft: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      proficiencyBonus: { type: 'integer' },
      inspiration: { type: 'boolean' },
      deathSaveSuccess: { type: 'integer' },
      deathSaveFail: { type: 'integer' },
      armorProf: stringArray,
      weaponProf: stringArray,
      toolProf: stringArray,
      languages: stringArray,
      skillProf: stringArray,
      skillExpertise: stringArray,
      saveProf: stringArray,
      features: {},
      spells: {},
      notes: { type: 'string', nullable: true },
      portraitUrl: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
      conditions: stringArray,
      exhaustionLevel: { type: 'integer' },
      locationId: { type: 'string', nullable: true },
    },
  },

  PlayerTravel: {
    type: 'object',
    required: ['destinationId', 'destination', 'route', 'legIndex', 'daysLeft'],
    properties: {
      destinationId: { type: 'string' },
      destination: { $ref: '#/components/schemas/Location' },
      route: { type: 'array', items: { type: 'string' } },
      legIndex: { type: 'integer' },
      daysLeft: { type: 'integer' },
    },
  },
  PlayerLocation: {
    type: 'object',
    required: ['playerId', 'location', 'travel'],
    properties: {
      playerId: { type: 'string' },
      location: { allOf: [{ $ref: '#/components/schemas/Location' }], nullable: true },
      travel: { allOf: [{ $ref: '#/components/schemas/PlayerTravel' }], nullable: true },
    },
  },

  LocationLink: {
    type: 'object',
    required: ['id', 'campaignId', 'fromId', 'toId', 'days', 'label'],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      fromId: { type: 'string' },
      toId: { type: 'string' },
      days: { type: 'integer' },
      label: { type: 'string', nullable: true },
    },
  },
  CreateLocationLink: {
    type: 'object',
    required: ['campaignId', 'fromId', 'toId', 'days'],
    properties: {
      campaignId: { type: 'string' },
      fromId: { type: 'string' },
      toId: { type: 'string' },
      days: { type: 'integer' },
      label: { type: 'string', nullable: true },
    },
  },
  UpdateLocationLink: {
    type: 'object',
    properties: {
      fromId: { type: 'string' },
      toId: { type: 'string' },
      days: { type: 'integer' },
      label: { type: 'string', nullable: true },
    },
  },

  Npc: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'name',
      'title',
      'appearance',
      'personality',
      'speech',
      'habits',
      'attitude',
      'dmNotes',
      'coinsCp',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      name: { type: 'string' },
      title: { type: 'string', nullable: true },
      appearance: { type: 'string' },
      personality: { type: 'string' },
      speech: { type: 'string' },
      habits: { type: 'string' },
      attitude: { type: 'string', nullable: true },
      dmNotes: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
    },
  },
  CreateNpc: {
    type: 'object',
    required: ['campaignId', 'name', 'title', 'appearance', 'personality', 'speech', 'habits', 'attitude', 'dmNotes'],
    properties: {
      campaignId: { type: 'string' },
      name: { type: 'string' },
      title: { type: 'string', nullable: true },
      appearance: { type: 'string' },
      personality: { type: 'string' },
      speech: { type: 'string' },
      habits: { type: 'string' },
      attitude: { type: 'string', nullable: true },
      dmNotes: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
    },
  },
  UpdateNpc: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      title: { type: 'string', nullable: true },
      appearance: { type: 'string' },
      personality: { type: 'string' },
      speech: { type: 'string' },
      habits: { type: 'string' },
      attitude: { type: 'string', nullable: true },
      dmNotes: { type: 'string', nullable: true },
      coinsCp: { type: 'integer' },
    },
  },

  NpcKnowledge: {
    type: 'object',
    required: ['id', 'npcId', 'title', 'content', 'reveal', 'skillHint', 'dc', 'questId'],
    properties: {
      id: { type: 'string' },
      npcId: { type: 'string' },
      title: { type: 'string' },
      content: { type: 'string' },
      reveal: { $ref: '#/components/schemas/KnowledgeReveal' },
      skillHint: { type: 'string', nullable: true },
      dc: { type: 'integer', nullable: true },
      questId: { type: 'string', nullable: true },
    },
  },
  CreateNpcKnowledgeBody: {
    type: 'object',
    required: ['title', 'content', 'reveal', 'skillHint', 'dc', 'questId'],
    properties: {
      title: { type: 'string' },
      content: { type: 'string' },
      reveal: { $ref: '#/components/schemas/KnowledgeReveal' },
      skillHint: { type: 'string', nullable: true },
      dc: { type: 'integer', nullable: true },
      questId: { type: 'string', nullable: true },
    },
  },
  UpdateNpcKnowledge: {
    type: 'object',
    properties: {
      title: { type: 'string' },
      content: { type: 'string' },
      reveal: { $ref: '#/components/schemas/KnowledgeReveal' },
      skillHint: { type: 'string', nullable: true },
      dc: { type: 'integer', nullable: true },
      questId: { type: 'string', nullable: true },
    },
  },

  NpcRelation: {
    type: 'object',
    required: ['npcId', 'playerId', 'score', 'note'],
    properties: {
      npcId: { type: 'string' },
      playerId: { type: 'string' },
      score: { type: 'integer', minimum: -100, maximum: 100 },
      note: { type: 'string', nullable: true },
    },
  },
  SetNpcRelationBody: {
    type: 'object',
    required: ['score'],
    properties: {
      score: { type: 'integer', minimum: -100, maximum: 100 },
      note: { type: 'string', nullable: true },
    },
  },

  NpcMemory: {
    type: 'object',
    required: ['id', 'npcId', 'playerId', 'summary', 'kind', 'importance'],
    properties: {
      id: { type: 'string' },
      npcId: { type: 'string' },
      playerId: { type: 'string', nullable: true },
      summary: { type: 'string' },
      kind: { $ref: '#/components/schemas/MemoryKind' },
      importance: { type: 'integer', minimum: 1, maximum: 5 },
    },
  },
  CreateNpcMemoryBody: {
    type: 'object',
    required: ['summary', 'kind'],
    properties: {
      playerId: { type: 'string', nullable: true },
      summary: { type: 'string' },
      kind: { $ref: '#/components/schemas/MemoryKind' },
      importance: { type: 'integer', minimum: 1, maximum: 5 },
    },
  },
  UpdateNpcMemory: {
    type: 'object',
    properties: {
      playerId: { type: 'string', nullable: true },
      summary: { type: 'string' },
      kind: { $ref: '#/components/schemas/MemoryKind' },
      importance: { type: 'integer', minimum: 1, maximum: 5 },
    },
  },

  NpcLocation: {
    type: 'object',
    required: ['npcId', 'locationId', 'role', 'isPrimary'],
    properties: {
      npcId: { type: 'string' },
      locationId: { type: 'string' },
      role: { type: 'string', nullable: true },
      isPrimary: { type: 'boolean' },
    },
  },
  SetNpcLocationBody: {
    type: 'object',
    required: ['locationId'],
    properties: {
      locationId: { type: 'string' },
      role: { type: 'string', nullable: true },
      isPrimary: { type: 'boolean' },
    },
  },

  NpcStatBlock: {
    type: 'object',
    required: [
      'id',
      'npcId',
      'size',
      'creatureType',
      'challengeRating',
      'proficiencyBonus',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'ac',
      'speed',
      'initiativeBonus',
      'saveProf',
      'resistances',
      'immunities',
      'vulnerabilities',
      'conditionImmunities',
      'senses',
      'languages',
      'traits',
      'actions',
      'reactions',
      'legendaryActions',
    ],
    properties: {
      id: { type: 'string' },
      npcId: { type: 'string' },
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
    },
  },
  UpsertNpcStatBlockBody: {
    type: 'object',
    required: [
      'size',
      'creatureType',
      'challengeRating',
      'proficiencyBonus',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'ac',
      'speed',
      'initiativeBonus',
      'saveProf',
      'resistances',
      'immunities',
      'vulnerabilities',
      'conditionImmunities',
      'senses',
      'languages',
      'traits',
      'actions',
      'reactions',
      'legendaryActions',
    ],
    properties: {
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
    },
  },

  CombatStats: {
    type: 'object',
    required: [
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'hpCurrent',
      'ac',
      'speed',
      'saveProf',
      'resistances',
      'immunities',
      'vulnerabilities',
      'conditionImmunities',
      'senses',
      'languages',
    ],
    properties: {
      name: { type: 'string' },
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      hpCurrent: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
    },
  },

  Quest: {
    type: 'object',
    required: ['id', 'campaignId', 'title', 'description', 'status', 'locationId'],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      title: { type: 'string' },
      description: { type: 'string' },
      status: { $ref: '#/components/schemas/QuestStatus' },
      locationId: { type: 'string', nullable: true },
    },
  },
  CreateQuest: {
    type: 'object',
    required: ['campaignId', 'title', 'description', 'locationId'],
    properties: {
      campaignId: { type: 'string' },
      title: { type: 'string' },
      description: { type: 'string' },
      status: { $ref: '#/components/schemas/QuestStatus' },
      locationId: { type: 'string', nullable: true },
    },
  },
  UpdateQuest: {
    type: 'object',
    properties: {
      title: { type: 'string' },
      description: { type: 'string' },
      status: { $ref: '#/components/schemas/QuestStatus' },
      locationId: { type: 'string', nullable: true },
    },
  },

  QuestNpc: {
    type: 'object',
    required: ['questId', 'npcId', 'role'],
    properties: {
      questId: { type: 'string' },
      npcId: { type: 'string' },
      role: { $ref: '#/components/schemas/QuestNpcRole' },
    },
  },
  AddQuestNpcBody: {
    type: 'object',
    required: ['npcId', 'role'],
    properties: {
      npcId: { type: 'string' },
      role: { $ref: '#/components/schemas/QuestNpcRole' },
    },
  },

  MonsterTemplate: {
    type: 'object',
    required: [
      'id',
      'campaignId',
      'name',
      'summary',
      'size',
      'creatureType',
      'challengeRating',
      'proficiencyBonus',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'ac',
      'speed',
      'initiativeBonus',
      'saveProf',
      'resistances',
      'immunities',
      'vulnerabilities',
      'conditionImmunities',
      'senses',
      'languages',
      'traits',
      'actions',
      'reactions',
      'legendaryActions',
      'lootCoinsCp',
    ],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      name: { type: 'string' },
      summary: { type: 'string', nullable: true },
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
      lootCoinsCp: { type: 'integer' },
    },
  },
  CreateMonsterTemplate: {
    type: 'object',
    required: [
      'campaignId',
      'name',
      'summary',
      'size',
      'creatureType',
      'challengeRating',
      'proficiencyBonus',
      'str',
      'dex',
      'con',
      'int',
      'wis',
      'cha',
      'hpMax',
      'ac',
      'speed',
      'initiativeBonus',
      'saveProf',
      'resistances',
      'immunities',
      'vulnerabilities',
      'conditionImmunities',
      'senses',
      'languages',
      'traits',
      'actions',
      'reactions',
      'legendaryActions',
    ],
    properties: {
      campaignId: { type: 'string' },
      name: { type: 'string' },
      summary: { type: 'string', nullable: true },
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
      lootCoinsCp: { type: 'integer' },
    },
  },
  UpdateMonsterTemplate: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      summary: { type: 'string', nullable: true },
      size: { type: 'string', nullable: true },
      creatureType: { type: 'string', nullable: true },
      challengeRating: { type: 'string', nullable: true },
      proficiencyBonus: { type: 'integer', nullable: true },
      ...abilities,
      hpMax: { type: 'integer' },
      ac: { type: 'integer' },
      speed: { type: 'integer' },
      initiativeBonus: { type: 'integer', nullable: true },
      saveProf: stringArray,
      resistances: stringArray,
      immunities: stringArray,
      vulnerabilities: stringArray,
      conditionImmunities: stringArray,
      senses: stringArray,
      languages: stringArray,
      traits: {},
      actions: {},
      reactions: {},
      legendaryActions: {},
      lootCoinsCp: { type: 'integer' },
    },
  },

  DiceRoll: {
    type: 'object',
    required: ['id', 'campaignId', 'die', 'value', 'note', 'playerId', 'npcId', 'rolledAt'],
    properties: {
      id: { type: 'string' },
      campaignId: { type: 'string' },
      die: { $ref: '#/components/schemas/DiceKind' },
      value: { type: 'integer' },
      note: { type: 'string', nullable: true },
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
      rolledAt: { type: 'string', format: 'date-time' },
    },
  },
  RollDice: {
    type: 'object',
    required: ['campaignId', 'die'],
    properties: {
      campaignId: { type: 'string' },
      die: { $ref: '#/components/schemas/DiceKind' },
      note: { type: 'string', nullable: true },
      playerId: { type: 'string', nullable: true },
      npcId: { type: 'string', nullable: true },
    },
  },

  CoinOwnerKind: {
    type: 'string',
    enum: ['player', 'npc', 'item'],
  },
  CoinOwner: {
    type: 'object',
    required: ['kind', 'id'],
    properties: {
      kind: { $ref: '#/components/schemas/CoinOwnerKind' },
      id: { type: 'string' },
    },
  },
  Coins: {
    type: 'object',
    required: ['pp', 'gp', 'ep', 'sp', 'cp'],
    properties: {
      pp: { type: 'integer' },
      gp: { type: 'integer' },
      ep: { type: 'integer' },
      sp: { type: 'integer' },
      cp: { type: 'integer' },
    },
  },
  CoinBalance: {
    type: 'object',
    required: ['owner', 'coinsCp', 'coins'],
    properties: {
      owner: { $ref: '#/components/schemas/CoinOwner' },
      coinsCp: { type: 'integer' },
      coins: { $ref: '#/components/schemas/Coins' },
    },
  },
  TransferCoins: {
    type: 'object',
    required: ['campaignId', 'from', 'to', 'amountCp'],
    properties: {
      campaignId: { type: 'string' },
      from: { $ref: '#/components/schemas/CoinOwner' },
      to: { $ref: '#/components/schemas/CoinOwner' },
      amountCp: { type: 'integer' },
    },
  },
  TransferCoinsResult: {
    type: 'object',
    required: ['from', 'to', 'amountCp'],
    properties: {
      from: { $ref: '#/components/schemas/CoinBalance' },
      to: { $ref: '#/components/schemas/CoinBalance' },
      amountCp: { type: 'integer' },
    },
  },
} as const;
